apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  argocd/app-name: chatbot2-apr29-2
  janus-idp.io/tekton: chatbot2-apr29-2
  backstage.io/kubernetes-id: chatbot2-apr29-2
  backstage.io/kubernetes-namespace: model2-apr29-1
  app.kubernetes.io/part-of: chatbot2-apr29-2
resources:
  - initialize-namespace/
  - deployment.yaml
  - route.yaml
  - service.yaml
  - model-config.yaml
